### PR TITLE
Update facts.js

### PR DESCRIPTION
**Pull request by Najem-Nabhani**
Quokkas are awesome :D

### CODE REVIEW

**Comment by Najem-Nabhani** [comment]
What's the issue with my pull request?

**Comment by amykapernick** [comment]
@MrN-Nabhani there's a couple of spelling mistakes in your facts, can you please fix them?

**Review by amykapernick — CHANGES_REQUESTED** [review]
Please spell check your facts

**Review by Najem-Nabhani — COMMENTED** [review]
Spelling mistakes fixed!

**Review by Najem-Nabhani — COMMENTED** [review]
fixed.

**Comment by amykapernick** [comment]
@Mergifyio refresh

**Comment by amykapernick** [comment]
@Mergifyio rebase

**Comment by amykapernick** [comment]
Unfortunately it seems like some other contributions have been merged since you contributed. Please resolve those merge conflicts. For more info check out this page: https://help.github.com/en/articles/resolving-a-merge-conflict-using-the-command-line

**Review by amykapernick — CHANGES_REQUESTED** [review]
Unfortunately it seems like some other contributions have been merged since you contributed. Please resolve those merge conflicts. For more info check out this page: https://help.github.com/en/articles/resolving-a-merge-conflict-using-the-command-line

**Comment by Najem-Nabhani** [comment]
I'm not familiar with the DevOps / bots stuff, so I don't really understand the issue here.
@amykapernick  can you help me?
is creating a new folk then a new PR solves the problem with merging?

**Comment by amykapernick** [comment]
@MrN-Nabhani there's been other changes added that now conflict with your changes, there's a doc on how to resolve it here - https://help.github.com/en/articles/resolving-a-merge-conflict-using-the-command-line or you may be able to resolve them via the web editor
image

**Pull request closed without merging**
